# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vote for ME!
email: 20kimmj@lasdk8.org
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Matthew! I am running for Financial officer, and this is my blog. VOTE for me!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mjaydenkim
github_username:  mjaydenkim

# Build settings
markdown: kramdown
